### ISSUE TITLE
problem with generics

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#1]
BoundBoxing a class with generics causes errors in the generated class (e.g. java.util.List&lt;this.is.my.Object>.class)﻿

Detailed issue: https://gist.github.com/flavienlaurent/6636457

**Comment by stephanenicolas** [comment]
Thanks for reporting this bug. The first ! wouuuww :)

It will take a few days, not that many, for me to correct the bug. Just have to find time for it.

I would be very interested by a pull request (with tests), if you like patching it yourself. 
I do invite with great pleasure new contributors to join.

(This feature / bug fix would be quite a good candidate for TDD style.)

**Comment by flavienlaurent** [comment]
I have to find time for it too but I will try to patch it

**Comment by stephanenicolas** [comment]
Issue should be solved on master branch. Your gist became a test. snapshots have been deployed on https://oss.sonatype.org/content/repositories/snapshots/org/boundbox/

**Comment by ffgiraldez** [comment]
I have the same problem but when generics are in Class like SpiceRequest<RESULT>
I have a class that extends SpiceRequest

```
public class MyRequest extends SpiceRequest<MyModel> {
    public MyRequest() {
        super(MyModel.class);
    }

   @Override
    public MyModel loadDataFromNetwork() throws Exception {
        return new MyModel();
    }
}
```

and in my test

```
public class MyRequestTest {
    @BoundBox(boundClass = MyRequest.class)
    private BoundBoxOfMyRequest request;
}
```

boundbox generated the nexts method un `BoundBoxOfMyRequest` class

`public java.lang.Class<RESULT> boundBox_getResultType();`

`public RESULT boundBox_super_SpiceRequest_loadDataFromNetwork()`

instead of 

`public java.lang.Class<MyModel> boundBox_getResultType();`

`public MyModel boundBox_super_SpiceRequest_loadDataFromNetwork()`

**Comment by stephanenicolas** [comment]
Hi flavien,

I really don't have much time to enhance BB these days, and 'til Xmas.
I am really concerned by this bug, but I can't investigate it further right
now. Any pull request / work on that would be appreciated.

Funny that you were the first user to use BB with RS, and I wasn't :)

S.

2013/11/8 Fernando Franco Gíraldez notifications@github.com

> I have the same problem but when generics are in Class like SpiceRequest
> I have a class that extends SpiceRequest
> 
> public class MyRequest extends SpiceRequest<MyModel> {
>     public MyRequest() {
>         super(MyModel.class);
>     }
> 
>    @Override
>     public MyModel loadDataFromNetwork() throws Exception {
>         return new MyModel();
>     }
> }
> 
> and in my test
> 
> public class MyRequestTest {
>     @BoundBox(boundClass = MyRequest.class)
>     private BoundBoxOfMyRequest request;
> }
> 
> boundbox generated the nexts method un BoundBoxOfMyRequest class
> 
> public java.lang.Class<RESULT> boundBox_getResultType();
> 
> public RESULT boundBox_super_SpiceRequest_loadDataFromNetwork()
> 
> instead of
> 
> public java.lang.Class<MyModel> boundBox_getResultType();
> 
> public MyModel boundBox_super_SpiceRequest_loadDataFromNetwork()
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/1#issuecomment-28045658
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by flavienlaurent** [comment]
Hi Stéphane,

Sorry, I can't work on BB anymore. I've too much project I must work on. I have certainly been overly ambitious in becoming a BB contributor. You can remove me from the contributor list if you want, no problem.

Flavien
