### ISSUE TITLE
remove m prefix in BoundBox class

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#14]
When BoundBoxing this kind of variable `private Button mButtonNext;`

Generate methods without 'm' prefix like `boundBox_getButtonNext()` instead of `boundBox_getMButtonNext()`

**Comment by stephanenicolas** [comment]
I am not that sure I would go in that direction. It's seen as a strong norm
in Android development for many teams.

Although I don't like it, I would not wish have to have this naming
convention unsupported de facto. Being optional this feature would give
much comfort.

S.
Le 30 sept. 2013 12:55, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by flavienlaurent** [comment]
I agree. An optional feature is a better solution

**Comment by stephanenicolas** [comment]
Sorry Flavien. I mistyped. I think that even optional it would not be that
much useful. I also fear that collisions of field names would be difficult
to handle.

But your opinion matters as much as mine ;) Feel free to implement it.

Stephane
Le 30 sept. 2013 13:18, "Stéphane NICOLAS" steff.nicolas@gmail.com a
écrit :

**Comment by flavienlaurent** [comment]
I'm gonna think about it. The more I think about it, the more it's not a really good idea. Moreover, it doesn't matter a lot because it's tool library ;)

**Comment by stephanenicolas** [comment]
I second. Nevertheless there are a couple of issues to tackle un the
backlog. If you feel like coding ;)

S.
Le 30 sept. 2013 18:42, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by flavienlaurent** [comment]
I feel like coding but unfortunatly, I don't have time to work on BoundBox these days.

**Comment by flavienlaurent** [comment]
Not a good idea :P
