### ISSUE TITLE
cast issue when BoundBoxing a custom view

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#2]
When boundboxing a custom view @BoundBox(boundClass = MyCustomView.class), the generated class contains errors:
- trying to cast Object to int, Object to boolean, Object to primitive type

```
public static int boundBox_getLAYOUT_DIRECTION_RTL() {
    try {
      Field field = View.class.getDeclaredField("LAYOUT_DIRECTION_RTL");
      field.setAccessible(true);
      return (int) field.get(null); // <-- problem
    }
    catch( Exception e ) {
      throw new BoundBoxException(e);
    }
  }
```
- LayoutParams import

```
The import com.my.pack.MyCustomView.LayoutParams collides with another import statement
```

**Comment by stephanenicolas** [comment]
The part with Statement conflict is a bit funny too me. I tried something but I am not sure. Would you mind to try the state of master branch, or current snapshots to say if bbug is fixed. If not, please add more details about the conflict and, ideally provide a small test/gist for it.

**Comment by flavienlaurent** [comment]
Statement conflict is still here.

https://gist.github.com/flavienlaurent/6667867

**Comment by stephanenicolas** [comment]
We are waiting for this pull request to be merged in JavaWriter. TODO uncomment a test in the writer when JavaWriter becomes mockable (non final) : 
https://github.com/square/javawriter/pull/25

**Comment by stephanenicolas** [comment]
Follow up.
Pull request has been merged. Close this thread when JavaWriter is released. 
TODO uncomment a test in the writer when JavaWriter becomes mockable (non final).

**Comment by stephanenicolas** [comment]
@flavienlaurent I will close the issue. But take care of changing your javawriter version for annotation processing in eclipse !

The text view test is now enabled in android-sample. That's really a nice test, very complex. The BoundBox is huge, but evrything seems fine.
