### ISSUE TITLE
documentation for contributor

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#3]
Could you provide some documentation about how to install the whole project?

**Comment by stephanenicolas** [comment]
What do you mean ? How to build it ? 
Here is a link in the wiki : https://github.com/stephanenicolas/boundbox/wiki/Contributors'-corner-:-building

Do you mean to explain how to setup the project in eclipse for contributors ?

Do you need any help to validate issue #2  is solved ?

**Comment by flavienlaurent** [comment]
I saw this link but there isn't any explaination on how to setup the project in IDE.

**Comment by flavienlaurent** [comment]
I don't need help to validate your fix but I would like to contribute adding some features ;)

**Comment by stephanenicolas** [comment]
Hi Falvien,

I jump on that. You will find a bunch of TODOs in the wiki. I am personally
 already thinking and designing on adding inner classes.
You might want to take another missing feature or join me on this one. I'am
also gonna add a feature on creating Javadoc inside the generated
boundboxes. It seems to me that such an issue would be a nice entry point
for a new contributor.

I would really appreciate tremendously that BoundBox remain _heavily_
tested. Very heavily. Do you feel like coding with lots of tests ?

I would be pleased to add you as an official contributor and give you the
rights to access the repo with writing perms. Do we say we try to work
together on a feature and then, if we both agree, make you an official
contributor ?

Stéphane
BTW, I can't work on the import issue (#2) before 2 days. You could also
tackle that issue (create tests and solve the bug).

2013/9/23 Flavien Laurent notifications@github.com

> I don't need help to validate your fix but I would like to contribute
> adding some features ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/3#issuecomment-24905140
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by stephanenicolas** [comment]
To setup the project in eclipse as a contributor, you can just read the
setup for users, the only difference as far as I remember is that each time
you change the annotation processor (i.e. BoundBox library), you will need
to reset it in projects that use it (i.e. first mvn clean install the
annotation processor, then re-set it inside projects that use it). That a
limitation of eclipse : it can't work with an annotation processor as a
project, you need to use the artifact. This procedure is also explained in
the normal setup for users.

I should find time soon to explain the process for contributors, you are
also welcome to do it. Don't repeat the procedure for boundbox users, just
expain what changes.

Stéphane

2013/9/23 Stéphane Nicolas snicolas@octo.com

> Hi Falvien,
> 
> I jump on that. You will find a bunch of TODOs in the wiki. I am
> personally  already thinking and designing on adding inner classes.
> You might want to take another missing feature or join me on this one.
> I'am also gonna add a feature on creating Javadoc inside the generated
> boundboxes. It seems to me that such an issue would be a nice entry point
> for a new contributor.
> 
> I would really appreciate tremendously that BoundBox remain _heavily_
> tested. Very heavily. Do you feel like coding with lots of tests ?
> 
> I would be pleased to add you as an official contributor and give you the
> rights to access the repo with writing perms. Do we say we try to work
> together on a feature and then, if we both agree, make you an official
> contributor ?
> 
> Stéphane
> BTW, I can't work on the import issue (#2) before 2 days. You could also
> tackle that issue (create tests and solve the bug).
> 
> 2013/9/23 Flavien Laurent notifications@github.com
> 
> > I don't need help to validate your fix but I would like to contribute
> > adding some features ;)
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/3#issuecomment-24905140
> > .
> 
> ## 
> 
> Stéphane _NICOLAS_,
> _OCTO Technology_
> Développeur & Consultant Android / Java
> ..........................................................
> 50, Avenue des Champs-Elysées
> 75008 Paris
> +33 (0)6.26.32.34.09
> www.octo.com - mobilite.octo.com
> blog.octo.com - www.usievents.com
> ...........................................................

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by flavienlaurent** [comment]
Finally succeed in installing the project into Eclipse.

Couple of tips:
- BoundBox uses Lombok (follow instructions here: http://projectlombok.org/mavenrepo/index.html)
- .factorypath files contain absolute paths like /Users/stephanenicolas/.m2/repository/[...]
- .factorypath files reference directly a BoundBox version (i.e. [...]1.0.0-SNAPSHOT/boundbox-library-1.0.0-SNAPSHOT.jar [...])
- Eclipse needs m2e-android (http://rgladwell.github.io/m2e-android/)
- Maven needs Android SDK to be deployed (thanks to https://github.com/mosabua/maven-android-sdk-deployer)

**Comment by stephanenicolas** [comment]
Would you take that task @flavienlaurent ? I can review it if you want.

**Comment by flavienlaurent** [comment]
Sure, I was going to ask you about it ;)
I'm on it!

**Comment by stephanenicolas** [comment]
Ok, I let assign your self to the issue so.

As you might have seen, JavaWriter's new release should be read tonight.

I hope to be able to put a last feature in for 1.1.0 : customizing boundbox
name and package.

Cool,
 S.

2013/9/26 Flavien Laurent notifications@github.com

> Sure, I was going to ask you about it ;)
> I'm on it!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/3#issuecomment-25153384
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by stephanenicolas** [comment]
This issue should be closed as well...
